
/* File generated by gen_cfile.py. Should not be modified. */

#include "Kinco_Ctrl.h"

/**************************************************************************/
/* Declaration of mapped variables                                        */
/**************************************************************************/
UNS16 ctrl_word = 0x00;		/* Mapped at index 0x2000, subindex 0x00 */
UNS32 target_pos = 0x0;		/* Mapped at index 0x2001, subindex 0x00 */
UNS16 Controlword = 0x0;		/* Mapped at index 0x6040, subindex 0x00 */
UNS16 Statusword = 0x0;		/* Mapped at index 0x6041, subindex 0x00 */
INTEGER32 Position_actual_value = 0x0;		/* Mapped at index 0x6064, subindex 0x00 */
INTEGER16 Current_actual_value = 0x0;		/* Mapped at index 0x6078, subindex 0x00 */
INTEGER32 Target_position = 0x0;		/* Mapped at index 0x607A, subindex 0x00 */
UNS32 Profile_velocity = 0x0;		/* Mapped at index 0x6081, subindex 0x00 */
INTEGER32 Target_velocity = 0x0;		/* Mapped at index 0x60FF, subindex 0x00 */

/**************************************************************************/
/* Declaration of value range types                                       */
/**************************************************************************/

#define valueRange_EMC 0x9F /* Type for index 0x1003 subindex 0x00 (only set of value 0 is possible) */
UNS32 Kinco_Ctrl_valueRangeTest(UNS8 typeValue, void* value)
{
  switch (typeValue) {
  case valueRange_EMC:
    if (*(UNS8*)value != (UNS8)0) return OD_VALUE_RANGE_EXCEEDED;
    break;
  }
  return 0;
}

/**************************************************************************/
/* The node id                                                            */
/**************************************************************************/
/* node_id default value.*/
UNS8 Kinco_Ctrl_bDeviceNodeId = 0x00;

/**************************************************************************/
/* Array of message processing information */

const UNS8 Kinco_Ctrl_iam_a_slave = 0;

TIMER_HANDLE Kinco_Ctrl_heartBeatTimers[1];

/*
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

                               OBJECT DICTIONARY

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
*/

/* index 0x1000 :   Device Type. */
UNS32 Kinco_Ctrl_obj1000 = 0x20192;	/* 131474 */
subindex Kinco_Ctrl_Index1000[] =
{
  { RO, uint32, sizeof(UNS32), (void*)&Kinco_Ctrl_obj1000 }
};

/* index 0x1001 :   Error Register. */
UNS8 Kinco_Ctrl_obj1001 = 0x0;	/* 0 */
subindex Kinco_Ctrl_Index1001[] =
{
  { RO, uint8, sizeof(UNS8), (void*)&Kinco_Ctrl_obj1001 }
};

/* index 0x1003 :   Pre-defined Error Field */
UNS8 Kinco_Ctrl_highestSubIndex_obj1003 = 0; /* number of subindex - 1*/
UNS32 Kinco_Ctrl_obj1003[] =
{
  0x0	/* 0 */
};
ODCallback_t Kinco_Ctrl_Index1003_callbacks[] =
{
  NULL,
  NULL,
};
subindex Kinco_Ctrl_Index1003[] =
{
  { RW, valueRange_EMC, sizeof(UNS8), (void*)&Kinco_Ctrl_highestSubIndex_obj1003 },
  { RO, uint32, sizeof(UNS32), (void*)&Kinco_Ctrl_obj1003[0] }
};

/* index 0x1005 :   SYNC COB ID. */
UNS32 Kinco_Ctrl_obj1005 = 0x40000080;	/* 1073741952 */
ODCallback_t Kinco_Ctrl_Index1005_callbacks[] =
{
  NULL,
};
subindex Kinco_Ctrl_Index1005[] =
{
  { RW, uint32, sizeof(UNS32), (void*)&Kinco_Ctrl_obj1005 }
};

/* index 0x1006 :   Communication / Cycle Period. */
UNS32 Kinco_Ctrl_obj1006 = 0xF4240;	/* 1000000 */
ODCallback_t Kinco_Ctrl_Index1006_callbacks[] =
{
  NULL,
};
subindex Kinco_Ctrl_Index1006[] =
{
  { RW, uint32, sizeof(UNS32), (void*)&Kinco_Ctrl_obj1006 }
};

/* index 0x1007 :   Synchronous Window Length. */
UNS32 Kinco_Ctrl_obj1007 = 0xF4240;	/* 1000000 */
subindex Kinco_Ctrl_Index1007[] =
{
  { RW, uint32, sizeof(UNS32), (void*)&Kinco_Ctrl_obj1007 }
};

/* index 0x100C :   Guard Time */
UNS16 Kinco_Ctrl_obj100C = 0x0;   /* 0 */

/* index 0x100D :   Life Time Factor */
UNS8 Kinco_Ctrl_obj100D = 0x0;   /* 0 */

/* index 0x1014 :   Emergency COB ID. */
UNS32 Kinco_Ctrl_obj1014 = 0x80;	/* 128 */
subindex Kinco_Ctrl_Index1014[] =
{
  { RW, uint32, sizeof(UNS32), (void*)&Kinco_Ctrl_obj1014 }
};

/* index 0x1016 :   Consumer Heartbeat Time */
UNS8 Kinco_Ctrl_highestSubIndex_obj1016 = 0;
UNS32 Kinco_Ctrl_obj1016[] = { 0 };

/* index 0x1017 :   Producer Heartbeat Time */
UNS16 Kinco_Ctrl_obj1017 = 0x0;   /* 0 */

/* index 0x1018 :   Identity. */
UNS8 Kinco_Ctrl_highestSubIndex_obj1018 = 4; /* number of subindex - 1*/
UNS32 Kinco_Ctrl_obj1018_Vendor_ID = 0x300;	/* 768 */
UNS32 Kinco_Ctrl_obj1018_Product_Code = 0x4644;	/* 17988 */
UNS32 Kinco_Ctrl_obj1018_Revision_Number = 0x0;	/* 0 */
UNS32 Kinco_Ctrl_obj1018_Serial_Number = 0x0;	/* 0 */
subindex Kinco_Ctrl_Index1018[] =
{
  { RO, uint8, sizeof(UNS8), (void*)&Kinco_Ctrl_highestSubIndex_obj1018 },
  { RO, uint32, sizeof(UNS32), (void*)&Kinco_Ctrl_obj1018_Vendor_ID },
  { RO, uint32, sizeof(UNS32), (void*)&Kinco_Ctrl_obj1018_Product_Code },
  { RO, uint32, sizeof(UNS32), (void*)&Kinco_Ctrl_obj1018_Revision_Number },
  { RO, uint32, sizeof(UNS32), (void*)&Kinco_Ctrl_obj1018_Serial_Number }
};

/* index 0x1280 :   Client SDO 1 Parameter. */
UNS8 Kinco_Ctrl_highestSubIndex_obj1280 = 3; /* number of subindex - 1*/
UNS32 Kinco_Ctrl_obj1280_COB_ID_Client_to_Server_Transmit_SDO = 0x601;	/* 1537 */
UNS32 Kinco_Ctrl_obj1280_COB_ID_Server_to_Client_Receive_SDO = 0x581;	/* 1409 */
UNS8 Kinco_Ctrl_obj1280_Node_ID_of_the_SDO_Server = 0x1;	/* 1 */
subindex Kinco_Ctrl_Index1280[] =
{
  { RO, uint8, sizeof(UNS8), (void*)&Kinco_Ctrl_highestSubIndex_obj1280 },
  { RW, uint32, sizeof(UNS32), (void*)&Kinco_Ctrl_obj1280_COB_ID_Client_to_Server_Transmit_SDO },
  { RW, uint32, sizeof(UNS32), (void*)&Kinco_Ctrl_obj1280_COB_ID_Server_to_Client_Receive_SDO },
  { RW, uint8, sizeof(UNS8), (void*)&Kinco_Ctrl_obj1280_Node_ID_of_the_SDO_Server }
};

/* index 0x1400 :   Receive PDO 1 Parameter. */
UNS8 Kinco_Ctrl_highestSubIndex_obj1400 = 6; /* number of subindex - 1*/
UNS32 Kinco_Ctrl_obj1400_COB_ID_used_by_PDO = 0x181;	/* 385 */
UNS8 Kinco_Ctrl_obj1400_Transmission_Type = 0x1;	/* 1 */
UNS16 Kinco_Ctrl_obj1400_Inhibit_Time = 0x0;	/* 0 */
UNS8 Kinco_Ctrl_obj1400_Compatibility_Entry = 0x0;	/* 0 */
UNS16 Kinco_Ctrl_obj1400_Event_Timer = 0x0;	/* 0 */
UNS8 Kinco_Ctrl_obj1400_SYNC_start_value = 0x0;	/* 0 */
subindex Kinco_Ctrl_Index1400[] =
{
  { RO, uint8, sizeof(UNS8), (void*)&Kinco_Ctrl_highestSubIndex_obj1400 },
  { RW, uint32, sizeof(UNS32), (void*)&Kinco_Ctrl_obj1400_COB_ID_used_by_PDO },
  { RW, uint8, sizeof(UNS8), (void*)&Kinco_Ctrl_obj1400_Transmission_Type },
  { RW, uint16, sizeof(UNS16), (void*)&Kinco_Ctrl_obj1400_Inhibit_Time },
  { RW, uint8, sizeof(UNS8), (void*)&Kinco_Ctrl_obj1400_Compatibility_Entry },
  { RW, uint16, sizeof(UNS16), (void*)&Kinco_Ctrl_obj1400_Event_Timer },
  { RW, uint8, sizeof(UNS8), (void*)&Kinco_Ctrl_obj1400_SYNC_start_value }
};

/* index 0x1401 :   Receive PDO 2 Parameter. */
UNS8 Kinco_Ctrl_highestSubIndex_obj1401 = 6; /* number of subindex - 1*/
UNS32 Kinco_Ctrl_obj1401_COB_ID_used_by_PDO = 0x181;	/* 385 */
UNS8 Kinco_Ctrl_obj1401_Transmission_Type = 0x1;	/* 1 */
UNS16 Kinco_Ctrl_obj1401_Inhibit_Time = 0x0;	/* 0 */
UNS8 Kinco_Ctrl_obj1401_Compatibility_Entry = 0x0;	/* 0 */
UNS16 Kinco_Ctrl_obj1401_Event_Timer = 0x0;	/* 0 */
UNS8 Kinco_Ctrl_obj1401_SYNC_start_value = 0x0;	/* 0 */
subindex Kinco_Ctrl_Index1401[] =
{
  { RO, uint8, sizeof(UNS8), (void*)&Kinco_Ctrl_highestSubIndex_obj1401 },
  { RW, uint32, sizeof(UNS32), (void*)&Kinco_Ctrl_obj1401_COB_ID_used_by_PDO },
  { RW, uint8, sizeof(UNS8), (void*)&Kinco_Ctrl_obj1401_Transmission_Type },
  { RW, uint16, sizeof(UNS16), (void*)&Kinco_Ctrl_obj1401_Inhibit_Time },
  { RW, uint8, sizeof(UNS8), (void*)&Kinco_Ctrl_obj1401_Compatibility_Entry },
  { RW, uint16, sizeof(UNS16), (void*)&Kinco_Ctrl_obj1401_Event_Timer },
  { RW, uint8, sizeof(UNS8), (void*)&Kinco_Ctrl_obj1401_SYNC_start_value }
};

/* index 0x1600 :   Receive PDO 1 Mapping. */
UNS8 Kinco_Ctrl_highestSubIndex_obj1600 = 2; /* number of subindex - 1*/
UNS32 Kinco_Ctrl_obj1600[] =
{
  0x60410010,	/* 1614872592 */
  0x60640020	/* 1617166368 */
};
subindex Kinco_Ctrl_Index1600[] =
{
  { RW, uint8, sizeof(UNS8), (void*)&Kinco_Ctrl_highestSubIndex_obj1600 },
  { RW, uint32, sizeof(UNS32), (void*)&Kinco_Ctrl_obj1600[0] },
  { RW, uint32, sizeof(UNS32), (void*)&Kinco_Ctrl_obj1600[1] }
};

/* index 0x1601 :   Receive PDO 2 Mapping. */
UNS8 Kinco_Ctrl_highestSubIndex_obj1601 = 1; /* number of subindex - 1*/
UNS32 Kinco_Ctrl_obj1601[] =
{
  0x60810020	/* 1619066912 */
};
subindex Kinco_Ctrl_Index1601[] =
{
  { RW, uint8, sizeof(UNS8), (void*)&Kinco_Ctrl_highestSubIndex_obj1601 },
  { RW, uint32, sizeof(UNS32), (void*)&Kinco_Ctrl_obj1601[0] }
};

/* index 0x1800 :   Transmit PDO 1 Parameter. */
UNS8 Kinco_Ctrl_highestSubIndex_obj1800 = 6; /* number of subindex - 1*/
UNS32 Kinco_Ctrl_obj1800_COB_ID_used_by_PDO = 0x201;	/* 513 */
UNS8 Kinco_Ctrl_obj1800_Transmission_Type = 0x1;	/* 1 */
UNS16 Kinco_Ctrl_obj1800_Inhibit_Time = 0x0;	/* 0 */
UNS8 Kinco_Ctrl_obj1800_Compatibility_Entry = 0x0;	/* 0 */
UNS16 Kinco_Ctrl_obj1800_Event_Timer = 0x0;	/* 0 */
UNS8 Kinco_Ctrl_obj1800_SYNC_start_value = 0x0;	/* 0 */
ODCallback_t Kinco_Ctrl_Index1800_callbacks[] =
{
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
};
subindex Kinco_Ctrl_Index1800[] =
{
  { RO, uint8, sizeof(UNS8), (void*)&Kinco_Ctrl_highestSubIndex_obj1800 },
  { RW, uint32, sizeof(UNS32), (void*)&Kinco_Ctrl_obj1800_COB_ID_used_by_PDO },
  { RW, uint8, sizeof(UNS8), (void*)&Kinco_Ctrl_obj1800_Transmission_Type },
  { RW, uint16, sizeof(UNS16), (void*)&Kinco_Ctrl_obj1800_Inhibit_Time },
  { RW, uint8, sizeof(UNS8), (void*)&Kinco_Ctrl_obj1800_Compatibility_Entry },
  { RW, uint16, sizeof(UNS16), (void*)&Kinco_Ctrl_obj1800_Event_Timer },
  { RW, uint8, sizeof(UNS8), (void*)&Kinco_Ctrl_obj1800_SYNC_start_value }
};

/* index 0x1A00 :   Transmit PDO 1 Mapping. */
UNS8 Kinco_Ctrl_highestSubIndex_obj1A00 = 2; /* number of subindex - 1*/
UNS32 Kinco_Ctrl_obj1A00[] =
{
  0x20000010,	/* 536870928 */
  0x20010020	/* 536936480 */
};
subindex Kinco_Ctrl_Index1A00[] =
{
  { RW, uint8, sizeof(UNS8), (void*)&Kinco_Ctrl_highestSubIndex_obj1A00 },
  { RW, uint32, sizeof(UNS32), (void*)&Kinco_Ctrl_obj1A00[0] },
  { RW, uint32, sizeof(UNS32), (void*)&Kinco_Ctrl_obj1A00[1] }
};

/* index 0x2000 :   Mapped variable ctrl_word */
subindex Kinco_Ctrl_Index2000[] =
{
  { RW, uint16, sizeof(UNS16), (void*)&ctrl_word, NULL }
};

/* index 0x2001 :   Mapped variable target_pos */
subindex Kinco_Ctrl_Index2001[] =
{
  { RW, uint32, sizeof(UNS32), (void*)&target_pos, NULL }
};

/* index 0x6040 :   Mapped variable Controlword */
subindex Kinco_Ctrl_Index6040[] =
{
  { RW, uint16, sizeof(UNS16), (void*)&Controlword }
};

/* index 0x6041 :   Mapped variable Statusword */
subindex Kinco_Ctrl_Index6041[] =
{
  { RO, uint16, sizeof(UNS16), (void*)&Statusword }
};

/* index 0x6064 :   Mapped variable Position actual value */
subindex Kinco_Ctrl_Index6064[] =
{
  { RO, int32, sizeof(INTEGER32), (void*)&Position_actual_value }
};

/* index 0x6078 :   Mapped variable Current actual value */
subindex Kinco_Ctrl_Index6078[] =
{
  { RO, int16, sizeof(INTEGER16), (void*)&Current_actual_value }
};

/* index 0x607A :   Mapped variable Target position */
subindex Kinco_Ctrl_Index607A[] =
{
  { RW, int32, sizeof(INTEGER32), (void*)&Target_position }
};

/* index 0x6081 :   Mapped variable Profile velocity */
subindex Kinco_Ctrl_Index6081[] =
{
  { RW, uint32, sizeof(UNS32), (void*)&Profile_velocity }
};

/* index 0x60FF :   Mapped variable Target velocity */
subindex Kinco_Ctrl_Index60FF[] =
{
  { RW, int32, sizeof(INTEGER32), (void*)&Target_velocity }
};

/**************************************************************************/
/* Declaration of pointed variables                                       */
/**************************************************************************/

const indextable Kinco_Ctrl_objdict[] =
{
  { (subindex*)Kinco_Ctrl_Index1000,sizeof(Kinco_Ctrl_Index1000) / sizeof(Kinco_Ctrl_Index1000[0]), 0x1000},
  { (subindex*)Kinco_Ctrl_Index1001,sizeof(Kinco_Ctrl_Index1001) / sizeof(Kinco_Ctrl_Index1001[0]), 0x1001},
  { (subindex*)Kinco_Ctrl_Index1005,sizeof(Kinco_Ctrl_Index1005) / sizeof(Kinco_Ctrl_Index1005[0]), 0x1005},
  { (subindex*)Kinco_Ctrl_Index1006,sizeof(Kinco_Ctrl_Index1006) / sizeof(Kinco_Ctrl_Index1006[0]), 0x1006},
  { (subindex*)Kinco_Ctrl_Index1007,sizeof(Kinco_Ctrl_Index1007) / sizeof(Kinco_Ctrl_Index1007[0]), 0x1007},
  { (subindex*)Kinco_Ctrl_Index1014,sizeof(Kinco_Ctrl_Index1014) / sizeof(Kinco_Ctrl_Index1014[0]), 0x1014},
  { (subindex*)Kinco_Ctrl_Index1018,sizeof(Kinco_Ctrl_Index1018) / sizeof(Kinco_Ctrl_Index1018[0]), 0x1018},
  { (subindex*)Kinco_Ctrl_Index1280,sizeof(Kinco_Ctrl_Index1280) / sizeof(Kinco_Ctrl_Index1280[0]), 0x1280},
  { (subindex*)Kinco_Ctrl_Index1400,sizeof(Kinco_Ctrl_Index1400) / sizeof(Kinco_Ctrl_Index1400[0]), 0x1400},
  { (subindex*)Kinco_Ctrl_Index1401,sizeof(Kinco_Ctrl_Index1401) / sizeof(Kinco_Ctrl_Index1401[0]), 0x1401},
  { (subindex*)Kinco_Ctrl_Index1600,sizeof(Kinco_Ctrl_Index1600) / sizeof(Kinco_Ctrl_Index1600[0]), 0x1600},
  { (subindex*)Kinco_Ctrl_Index1601,sizeof(Kinco_Ctrl_Index1601) / sizeof(Kinco_Ctrl_Index1601[0]), 0x1601},
  { (subindex*)Kinco_Ctrl_Index1800,sizeof(Kinco_Ctrl_Index1800) / sizeof(Kinco_Ctrl_Index1800[0]), 0x1800},
  { (subindex*)Kinco_Ctrl_Index1A00,sizeof(Kinco_Ctrl_Index1A00) / sizeof(Kinco_Ctrl_Index1A00[0]), 0x1A00},
  { (subindex*)Kinco_Ctrl_Index2000,sizeof(Kinco_Ctrl_Index2000) / sizeof(Kinco_Ctrl_Index2000[0]), 0x2000},
  { (subindex*)Kinco_Ctrl_Index2001,sizeof(Kinco_Ctrl_Index2001) / sizeof(Kinco_Ctrl_Index2001[0]), 0x2001},
  { (subindex*)Kinco_Ctrl_Index6040,sizeof(Kinco_Ctrl_Index6040) / sizeof(Kinco_Ctrl_Index6040[0]), 0x6040},
  { (subindex*)Kinco_Ctrl_Index6041,sizeof(Kinco_Ctrl_Index6041) / sizeof(Kinco_Ctrl_Index6041[0]), 0x6041},
  { (subindex*)Kinco_Ctrl_Index6064,sizeof(Kinco_Ctrl_Index6064) / sizeof(Kinco_Ctrl_Index6064[0]), 0x6064},
  { (subindex*)Kinco_Ctrl_Index6078,sizeof(Kinco_Ctrl_Index6078) / sizeof(Kinco_Ctrl_Index6078[0]), 0x6078},
  { (subindex*)Kinco_Ctrl_Index607A,sizeof(Kinco_Ctrl_Index607A) / sizeof(Kinco_Ctrl_Index607A[0]), 0x607A},
  { (subindex*)Kinco_Ctrl_Index6081,sizeof(Kinco_Ctrl_Index6081) / sizeof(Kinco_Ctrl_Index6081[0]), 0x6081},
  { (subindex*)Kinco_Ctrl_Index60FF,sizeof(Kinco_Ctrl_Index60FF) / sizeof(Kinco_Ctrl_Index60FF[0]), 0x60FF},
};

const indextable* Kinco_Ctrl_scanIndexOD(CO_Data* d, UNS16 wIndex, UNS32* errorCode)
{
  // printf("wIndex=0x%x\r\n", wIndex);
  (void)d;
  int i;
  switch (wIndex) {
  case 0x1000: i = 0;break;
  case 0x1001: i = 1;break;
  case 0x1005: i = 2;break;
  case 0x1006: i = 3;break;
  case 0x1007: i = 4;break;
  case 0x1014: i = 5;break;
  case 0x1018: i = 6;break;
  case 0x1280: i = 7;break;
  case 0x1400: i = 8;break;
  case 0x1401: i = 9;break;
  case 0x1600: i = 10;break;
  case 0x1601: i = 11;break;
  case 0x1800: i = 12;break;
  case 0x1A00: i = 13;break;
  case 0x2000: i = 14;break;
  case 0x2001: i = 15;break;
  case 0x6040: i = 16;break;
  case 0x6041: i = 17;break;
  case 0x6064: i = 18;break;
  case 0x6078: i = 19;break;
  case 0x607A: i = 20;break;
  case 0x6081: i = 21;break;
  case 0x60FF: i = 22;break;
  default:
    *errorCode = OD_NO_SUCH_OBJECT;
    return NULL;
  }
  *errorCode = OD_SUCCESSFUL;
  return &Kinco_Ctrl_objdict[i];
}

/*
 * To count at which received SYNC a PDO must be sent.
 * Even if no pdoTransmit are defined, at least one entry is computed
 * for compilations issues.
 */
s_PDO_status Kinco_Ctrl_PDO_status[1] = { s_PDO_status_Initializer };

const quick_index Kinco_Ctrl_firstIndex = {
  0, /* SDO_SVR */
  7, /* SDO_CLT */
  8, /* PDO_RCV */
  10, /* PDO_RCV_MAP */
  12, /* PDO_TRS */
  13 /* PDO_TRS_MAP */
};

const quick_index Kinco_Ctrl_lastIndex = {
  0, /* SDO_SVR */
  7, /* SDO_CLT */
  9, /* PDO_RCV */
  11, /* PDO_RCV_MAP */
  12, /* PDO_TRS */
  13 /* PDO_TRS_MAP */
};

const UNS16 Kinco_Ctrl_ObjdictSize = sizeof(Kinco_Ctrl_objdict) / sizeof(Kinco_Ctrl_objdict[0]);

CO_Data Kinco_Ctrl_Data = CANOPEN_NODE_DATA_INITIALIZER(Kinco_Ctrl);

