
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef KINCO_CTRL_H
#define KINCO_CTRL_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 Kinco_Ctrl_valueRangeTest(UNS8 typeValue, void* value);
const indextable* Kinco_Ctrl_scanIndexOD(CO_Data* d, UNS16 wIndex, UNS32* errorCode);

/* Master node data struct */
extern CO_Data Kinco_Ctrl_Data;
extern UNS16 ctrl_word;		/* Mapped at index 0x2000, subindex 0x00*/
extern UNS32 target_pos;		/* Mapped at index 0x2001, subindex 0x00*/
extern UNS32 target_vel;		/* Mapped at index 0x2002, subindex 0x00*/
extern UNS16 Controlword;		/* Mapped at index 0x6040, subindex 0x00*/
extern UNS16 Statusword;		/* Mapped at index 0x6041, subindex 0x00*/
extern INTEGER32 Position_actual_value;		/* Mapped at index 0x6064, subindex 0x00*/
extern INTEGER16 Current_actual_value;		/* Mapped at index 0x6078, subindex 0x00*/
extern INTEGER32 Target_position;		/* Mapped at index 0x607A, subindex 0x00*/
extern UNS32 Profile_velocity;		/* Mapped at index 0x6081, subindex 0x00*/
extern INTEGER32 Target_velocity;		/* Mapped at index 0x60FF, subindex 0x00*/

#endif // KINCO_CTRL_H
