///**
// * @file uart_bsp.h
// * @brief 串口BSP层驱动头文件
// * @details 设计为与CubeMX生成的代码配合使用，提供扩展的UART功能
// * @author Generated by Claude
// * @date 2025-03-10
// */

//#ifndef UART_BSP_H
//#define UART_BSP_H

//#include <stdint.h>
//#include <stdbool.h>
//#include "main.h"
//#include "cmsis_os.h"

///**
// * @brief 串口ID枚举
// */
//typedef enum {
//    UART_ID_1 = 0,  // 调试串口，DMA发送和接收
//    UART_ID_2,      // 传感器串口，仅DMA接收
//    UART_ID_3,      // RS485通信串口，DMA发送和接收，支持Modbus
//    UART_ID_MAX     // 串口数量
//} UART_ID_E;

///**
// * @brief 串口状态枚举
// */
//typedef enum {
//    UART_OK = 0,           // 操作成功
//    UART_ERROR,            // 一般错误
//    UART_BUSY,             // 串口忙
//    UART_TIMEOUT,          // 操作超时
//    UART_PARAM_INVALID,    // 参数无效
//    UART_BUFFER_OVERFLOW,  // 缓冲区溢出
//    UART_NO_BUFFER         // 无可用缓冲区
//} UART_Status_t;

///**
// * @brief 串口接收缓冲区结构体
// */
//typedef struct {
//    uint8_t *data;         // 数据指针
//    uint16_t size;         // 缓冲区大小
//    uint16_t length;       // 实际数据长度
//    bool in_use;           // 是否在使用中
//    uint32_t timestamp;    // 时间戳
//} UART_RxBuffer_t;

///**
// * @brief 串口接收回调函数类型
// */
//typedef void (*UART_RxCallback_t)(UART_ID_E id, uint8_t *data, uint16_t size);

///**
// * @brief 串口DMA+空闲中断接收配置
// * @param id 串口ID
// * @param queue_handle CubeMX生成的消息队列句柄
// * @param buffer_pool 接收缓冲区池指针
// * @param buffer_count 缓冲区数量
// * @param buffer_size 每个缓冲区的大小
// * @param rx_callback 可选的直接回调函数
// * @return UART_Status_t 配置状态
// */
//UART_Status_t UART_ConfigDmaIdleRx(UART_ID_E id, 
//                                  osMessageQId queue_handle,
//                                  UART_RxBuffer_t *buffer_pool, 
//                                  uint8_t buffer_count,
//                                  uint16_t buffer_size,
//                                  UART_RxCallback_t rx_callback);

///**
// * @brief 串口DMA发送配置
// * @param id 串口ID
// * @param queue_handle CubeMX生成的发送消息队列句柄(可选，可为NULL)
// * @return UART_Status_t 配置状态
// */
//UART_Status_t UART_ConfigDmaTx(UART_ID_E id, osMessageQId queue_handle);

///**
// * @brief 启动串口DMA+空闲中断接收
// * @param id 串口ID
// * @return UART_Status_t 操作状态
// */
//UART_Status_t UART_StartDmaRx(UART_ID_E id);

///**
// * @brief 发送数据
// * @param id 串口ID
// * @param data 数据指针
// * @param size 数据大小
// * @return UART_Status_t 操作状态
// */
//UART_Status_t UART_Transmit(UART_ID_E id, const uint8_t *data, uint16_t size);

///**
// * @brief 发送字符串
// * @param id 串口ID
// * @param str 字符串指针
// * @return UART_Status_t 操作状态
// */
//UART_Status_t UART_TransmitString(UART_ID_E id, const char *str);

///**
// * @brief 从缓冲区池中分配缓冲区
// * @param buffer_pool 缓冲区池指针
// * @param buffer_count 缓冲区数量
// * @return UART_RxBuffer_t* 分配的缓冲区指针，如果没有可用缓冲区则返回NULL
// */
//UART_RxBuffer_t* UART_AllocateBuffer(UART_RxBuffer_t *buffer_pool, uint8_t buffer_count);

///**
// * @brief 释放缓冲区
// * @param buffer 待释放的缓冲区指针
// */
//void UART_ReleaseBuffer(UART_RxBuffer_t *buffer);

///**
// * @brief UART错误处理函数
// * @param id 串口ID
// */
//void UART_ErrorHandler(UART_ID_E id);

///**
// * @brief 获取UART统计信息
// * @param id 串口ID
// * @param rx_count 接收帧计数
// * @param rx_bytes 接收字节计数
// * @param tx_count 发送帧计数
// * @param tx_bytes 发送字节计数
// * @param error_count 错误计数
// */
//void UART_GetStats(UART_ID_E id, uint32_t *rx_count, uint32_t *rx_bytes, 
//                   uint32_t *tx_count, uint32_t *tx_bytes, uint32_t *error_count);

///**
// * @brief 重置UART统计信息
// * @param id 串口ID
// */
//void UART_ResetStats(UART_ID_E id);

///* 以下函数需要在STM32 HAL回调中调用 */

///**
// * @brief 串口接收完成回调函数(需要在HAL_UART_RxCpltCallback中调用)
// * @param huart HAL UART句柄
// */
//void UART_BSP_RxCpltCallback(UART_HandleTypeDef *huart);

///**
// * @brief 串口发送完成回调函数(需要在HAL_UART_TxCpltCallback中调用)
// * @param huart HAL UART句柄
// */
//void UART_BSP_TxCpltCallback(UART_HandleTypeDef *huart);

///**
// * @brief 串口空闲中断回调函数(需要在串口中断处理函数中调用)
// * @param huart HAL UART句柄
// */
//void UART_BSP_IdleCallback(UART_HandleTypeDef *huart);

///**
// * @brief 串口错误回调函数(需要在HAL_UART_ErrorCallback中调用)
// * @param huart HAL UART句柄
// */
//void UART_BSP_ErrorCallback(UART_HandleTypeDef *huart);

//#endif /* UART_BSP_H */