///**
// * @file uart_bsp.c
// * @brief 串口BSP层驱动实现文件
// * @details 提供与CubeMX生成的代码配合使用的UART扩展功能
// * @author Generated by Claude
// * @date 2025-03-10
// */

//#include "uart_bsp.h"
//#include "string.h"

///* 外部变量声明 - 来自CubeMX生成的代码 */
//extern UART_HandleTypeDef huart1;
//extern UART_HandleTypeDef huart2;
//extern UART_HandleTypeDef huart3;
//extern DMA_HandleTypeDef hdma_usart1_rx;
//extern DMA_HandleTypeDef hdma_usart1_tx;
//extern DMA_HandleTypeDef hdma_usart2_rx;
//extern DMA_HandleTypeDef hdma_usart3_rx;
//extern DMA_HandleTypeDef hdma_usart3_tx;

///* 私有类型定义 */

///**
// * @brief UART通道控制结构体
// */
//typedef struct {
//    UART_HandleTypeDef *huart;          // UART HAL句柄
//    DMA_HandleTypeDef *hdma_rx;         // 接收DMA句柄
//    DMA_HandleTypeDef *hdma_tx;         // 发送DMA句柄
//    uint8_t *dma_rx_buffer;             // DMA接收缓冲区
//    uint16_t dma_rx_size;               // DMA接收缓冲区大小
//    uint8_t *tx_buffer;                 // 发送缓冲区
//    uint16_t tx_buffer_size;            // 发送缓冲区大小
//    uint16_t tx_size;                   // 当前发送大小
//    bool tx_busy;                       // 发送忙标志
//    osMessageQId rx_queue;              // 接收队列句柄(CubeMX生成)
//    osMessageQId tx_queue;              // 发送队列句柄(CubeMX生成)
//    UART_RxBuffer_t *rx_buffer_pool;    // 接收缓冲区池
//    uint8_t rx_buffer_count;            // 接收缓冲区数量
//    UART_RxBuffer_t *current_rx_buffer; // 当前DMA接收缓冲区
//    UART_RxCallback_t rx_callback;      // 接收回调函数

//    struct {
//        uint32_t rx_frames;             // 接收帧计数
//        uint32_t rx_bytes;              // 接收字节计数
//        uint32_t tx_frames;             // 发送帧计数
//        uint32_t tx_bytes;              // 发送字节计数
//        uint32_t errors;                // 错误计数
//        uint32_t buffer_overflow;       // 缓冲区溢出计数
//        uint32_t no_buffer;             // 无可用缓冲区计数
//    } stats;
//    
//    osMutexId tx_mutex;                 // 发送互斥锁
//} UART_Channel_t;

///* 私有变量 */
//static UART_Channel_t uart_channels[UART_ID_MAX];
//static const char *error_string = "[UART ERROR]\r\n"; // 错误提示字符串

///* 私有函数声明 */
//static void UART_InitMutex(UART_ID_E id);
//static UART_HandleTypeDef* UART_GetHuart(UART_ID_E id);
//static void UART_ProcessTxQueue(UART_ID_E id);
//static void UART_InitChannel(UART_ID_E id);
//static void UART_SendErrorMessage(UART_ID_E id);

///* 函数实现 */

///**
// * @brief 串口DMA+空闲中断接收配置
// */
//UART_Status_t UART_ConfigDmaIdleRx(UART_ID_E id, 
//                                  osMessageQId queue_handle,
//                                  UART_RxBuffer_t *buffer_pool, 
//                                  uint8_t buffer_count,
//                                  uint16_t buffer_size,
//                                  UART_RxCallback_t rx_callback)
//{
//    if (id >= UART_ID_MAX || buffer_pool == NULL || buffer_count == 0 || buffer_size == 0) {
//        return UART_PARAM_INVALID;
//    }
//    
//    /* 初始化通道 */
//    UART_InitChannel(id);
//    
//    /* 保存配置 */
//    UART_Channel_t *channel = &uart_channels[id];
//    channel->rx_queue = queue_handle;
//    channel->rx_buffer_pool = buffer_pool;
//    channel->rx_buffer_count = buffer_count;
//    channel->rx_callback = rx_callback;
//    
//    /* 初始化缓冲区池 */
//    for (uint8_t i = 0; i < buffer_count; i++) {
//        buffer_pool[i].data = (uint8_t*)malloc(buffer_size);
//        if (buffer_pool[i].data == NULL) {
//            /* 内存分配失败，释放之前分配的内存 */
//            for (uint8_t j = 0; j < i; j++) {
//                free(buffer_pool[j].data);
//                buffer_pool[j].data = NULL;
//            }
//            return UART_ERROR;
//        }
//        buffer_pool[i].size = buffer_size;
//        buffer_pool[i].length = 0;
//        buffer_pool[i].in_use = false;
//        buffer_pool[i].timestamp = 0;
//    }
//    
//    return UART_OK;
//}

///**
// * @brief 串口DMA发送配置
// */
//UART_Status_t UART_ConfigDmaTx(UART_ID_E id, osMessageQId queue_handle)
//{
//    if (id >= UART_ID_MAX) {
//        return UART_PARAM_INVALID;
//    }
//    
//    /* 初始化通道 */
//    UART_InitChannel(id);
//    
//    /* 保存发送队列句柄 */
//    UART_Channel_t *channel = &uart_channels[id];
//    channel->tx_queue = queue_handle;
//    
//    /* 初始化发送缓冲区 */
//    channel->tx_buffer_size = 256; /* 可根据需要调整 */
//    channel->tx_buffer = (uint8_t*)malloc(channel->tx_buffer_size);
//    if (channel->tx_buffer == NULL) {
//        return UART_ERROR;
//    }
//    
//    /* 初始化发送互斥锁 */
//    UART_InitMutex(id);
//    
//    return UART_OK;
//}

///**
// * @brief 启动串口DMA+空闲中断接收
// */
//UART_Status_t UART_StartDmaRx(UART_ID_E id)
//{
//    if (id >= UART_ID_MAX) {
//        return UART_PARAM_INVALID;
//    }
//    
//    UART_Channel_t *channel = &uart_channels[id];
//    UART_HandleTypeDef *huart = channel->huart;
//    
//    if (huart == NULL) {
//        return UART_ERROR;
//    }
//    
//    /* 分配接收缓冲区 */
//    channel->current_rx_buffer = UART_AllocateBuffer(channel->rx_buffer_pool, channel->rx_buffer_count);
//    if (channel->current_rx_buffer == NULL) {
//        channel->stats.no_buffer++;
//        return UART_NO_BUFFER;
//    }
//    
//    /* 启动DMA接收 */
//    if (HAL_UART_Receive_DMA(huart, channel->current_rx_buffer->data, channel->current_rx_buffer->size) != HAL_OK) {
//        UART_ReleaseBuffer(channel->current_rx_buffer);
//        channel->current_rx_buffer = NULL;
//        channel->stats.errors++;
//        return UART_ERROR;
//    }
//    
//    /* 启用空闲中断 */
//    __HAL_UART_ENABLE_IT(huart, UART_IT_IDLE);
//    
//    return UART_OK;
//}

///**
// * @brief 发送数据
// */
//UART_Status_t UART_Transmit(UART_ID_E id, const uint8_t *data, uint16_t size)
//{
//    if (id >= UART_ID_MAX || data == NULL || size == 0) {
//        return UART_PARAM_INVALID;
//    }
//    
//    UART_Channel_t *channel = &uart_channels[id];
//    UART_HandleTypeDef *huart = channel->huart;
//    
//    if (huart == NULL) {
//        return UART_ERROR;
//    }
//    
//    /* 获取互斥锁 */
//    if (osMutexWait(channel->tx_mutex, 100) != osOK) {
//        return UART_BUSY;
//    }
//    
//    /* 检查是否忙 */
//    if (channel->tx_busy) {
//        osMutexRelease(channel->tx_mutex);
//        return UART_BUSY;
//    }
//    
//    /* 复制数据到发送缓冲区 */
//    uint16_t copy_size = (size > channel->tx_buffer_size) ? channel->tx_buffer_size : size;
//    memcpy(channel->tx_buffer, data, copy_size);
//    channel->tx_size = copy_size;
//    channel->tx_busy = true;
//    
//    /* 发送数据 */
//    HAL_StatusTypeDef hal_status = HAL_UART_Transmit_DMA(huart, channel->tx_buffer, copy_size);
//    if (hal_status != HAL_OK) {
//        channel->tx_busy = false;
//        channel->stats.errors++;
//        osMutexRelease(channel->tx_mutex);
//        return UART_ERROR;
//    }
//    
//    /* 更新统计 */
//    channel->stats.tx_frames++;
//    channel->stats.tx_bytes += copy_size;
//    
//    osMutexRelease(channel->tx_mutex);
//    return UART_OK;
//}

///**
// * @brief 发送字符串
// */
//UART_Status_t UART_TransmitString(UART_ID_E id, const char *str)
//{
//    if (str == NULL) {
//        return UART_PARAM_INVALID;
//    }
//    
//    return UART_Transmit(id, (const uint8_t*)str, strlen(str));
//}

///**
// * @brief 从缓冲区池中分配缓冲区
// */
//UART_RxBuffer_t* UART_AllocateBuffer(UART_RxBuffer_t *buffer_pool, uint8_t buffer_count)
//{
//    if (buffer_pool == NULL || buffer_count == 0) {
//        return NULL;
//    }
//    
//    /* 寻找可用缓冲区 */
//    for (uint8_t i = 0; i < buffer_count; i++) {
//        if (!buffer_pool[i].in_use) {
//            buffer_pool[i].in_use = true;
//            buffer_pool[i].length = 0;
//            buffer_pool[i].timestamp = HAL_GetTick();
//            return &buffer_pool[i];
//        }
//    }
//    
//    /* 没有可用缓冲区 */
//    return NULL;
//}

///**
// * @brief 释放缓冲区
// */
//void UART_ReleaseBuffer(UART_RxBuffer_t *buffer)
//{
//    if (buffer != NULL) {
//        buffer->in_use = false;
//        buffer->length = 0;
//    }
//}

///**
// * @brief UART错误处理函数
// */
//void UART_ErrorHandler(UART_ID_E id)
//{
//    if (id >= UART_ID_MAX) {
//        return;
//    }
//    
//    UART_Channel_t *channel = &uart_channels[id];
//    channel->stats.errors++;
//    
//    /* 发送错误信息到调试串口 */
//    UART_SendErrorMessage(id);
//    
//    /* 重启接收 */
//    if (channel->current_rx_buffer != NULL) {
//        UART_ReleaseBuffer(channel->current_rx_buffer);
//        channel->current_rx_buffer = NULL;
//    }
//    UART_StartDmaRx(id);
//}

///**
// * @brief 获取UART统计信息
// */
//void UART_GetStats(UART_ID_E id, uint32_t *rx_count, uint32_t *rx_bytes, 
//                   uint32_t *tx_count, uint32_t *tx_bytes, uint32_t *error_count)
//{
//    if (id >= UART_ID_MAX) {
//        return;
//    }
//    
//    UART_Channel_t *channel = &uart_channels[id];
//    
//    if (rx_count != NULL) {
//        *rx_count = channel->stats.rx_frames;
//    }
//    
//    if (rx_bytes != NULL) {
//        *rx_bytes = channel->stats.rx_bytes;
//    }
//    
//    if (tx_count != NULL) {
//        *tx_count = channel->stats.tx_frames;
//    }
//    
//    if (tx_bytes != NULL) {
//        *tx_bytes = channel->stats.tx_bytes;
//    }
//    
//    if (error_count != NULL) {
//        *error_count = channel->stats.errors;
//    }
//}

///**
// * @brief 重置UART统计信息
// */
//void UART_ResetStats(UART_ID_E id)
//{
//    if (id >= UART_ID_MAX) {
//        return;
//    }
//    
//    UART_Channel_t *channel = &uart_channels[id];
//    memset(&channel->stats, 0, sizeof(channel->stats));
//}

///**
// * @brief 串口接收完成回调函数
// */
//void UART_BSP_RxCpltCallback(UART_HandleTypeDef *huart)
//{
//    /* 确定是哪个串口 */
//    UART_ID_E id = UART_ID_MAX;
//    
//    if (huart == &huart1) {
//        id = UART_ID_1;
//    } else if (huart == &huart2) {
//        id = UART_ID_2;
//    } else if (huart == &huart3) {
//        id = UART_ID_3;
//    } else {
//        return;
//    }
//    
//    /* 处理接收完成事件 - 对于DMA+空闲模式，这个回调通常不会被调用 */
//    UART_Channel_t *channel = &uart_channels[id];
//    
//    /* 更新统计 */
//    channel->stats.rx_frames++;
//}

///**
// * @brief 串口发送完成回调函数
// */
//void UART_BSP_TxCpltCallback(UART_HandleTypeDef *huart)
//{
//    /* 确定是哪个串口 */
//    UART_ID_E id = UART_ID_MAX;
//    
//    if (huart == &huart1) {
//        id = UART_ID_1;
//    } else if (huart == &huart2) {
//        id = UART_ID_2;
//    } else if (huart == &huart3) {
//        id = UART_ID_3;
//    } else {
//        return;
//    }
//    
//    /* 处理发送完成事件 */
//    UART_Channel_t *channel = &uart_channels[id];
//    
//    /* 获取互斥锁 */
//    if (osMutexWait(channel->tx_mutex, 10) != osOK) {
//        return;
//    }
//    
//    /* 清除忙标志 */
//    channel->tx_busy = false;
//    
//    /* 如果有发送队列，处理下一个发送请求 */
//    if (channel->tx_queue != NULL) {
//        UART_ProcessTxQueue(id);
//    }
//    
//    osMutexRelease(channel->tx_mutex);
//}

///**
// * @brief 串口空闲中断回调函数
// */
//void UART_BSP_IdleCallback(UART_HandleTypeDef *huart)
//{
//    /* 确定是哪个串口 */
//    UART_ID_E id = UART_ID_MAX;
//    
//    if (huart == &huart1) {
//        id = UART_ID_1;
//    } else if (huart == &huart2) {
//        id = UART_ID_2;
//    } else if (huart == &huart3) {
//        id = UART_ID_3;
//    } else {
//        return;
//    }
//    
//    /* 清除空闲标志 */
//    __HAL_UART_CLEAR_IDLEFLAG(huart);
//    
//    /* 处理接收到的数据 */
//    UART_Channel_t *channel = &uart_channels[id];
//    
//    /* 如果没有当前接收缓冲区，则返回 */
//    if (channel->current_rx_buffer == NULL) {
//        return;
//    }
//    
//    /* 停止DMA接收 */
//    HAL_UART_AbortReceive(huart);
//    
//    /* 计算接收到的数据长度 */
//    uint16_t dma_pos = channel->current_rx_buffer->size - __HAL_DMA_GET_COUNTER(channel->hdma_rx);
//    channel->current_rx_buffer->length = dma_pos;
//    
//    /* 如果接收到数据 */
//    if (dma_pos > 0) {
//        /* 更新统计 */
//        channel->stats.rx_frames++;
//        channel->stats.rx_bytes += dma_pos;
//        
//        /* 如果有回调函数，执行回调 */
//        if (channel->rx_callback != NULL) {
//            channel->rx_callback(id, channel->current_rx_buffer->data, dma_pos);
//        }
//        
//        /* 如果有接收队列，将缓冲区放入队列 */
//        if (channel->rx_queue != NULL) {
//            /* 发送缓冲区指针到队列 */
//            if (osMessagePut(channel->rx_queue, (uint32_t)channel->current_rx_buffer, 0) != osOK) {
//                /* 队列已满，释放缓冲区 */
//                UART_ReleaseBuffer(channel->current_rx_buffer);
//                channel->stats.buffer_overflow++;
//            }
//            channel->current_rx_buffer = NULL;
//        } else {
//            /* 没有队列，直接释放缓冲区 */
//            UART_ReleaseBuffer(channel->current_rx_buffer);
//            channel->current_rx_buffer = NULL;
//        }
//    } else {
//        /* 没有接收到数据，释放缓冲区 */
//        UART_ReleaseBuffer(channel->current_rx_buffer);
//        channel->current_rx_buffer = NULL;
//    }
//    
//    /* 重新启动接收 */
//    UART_StartDmaRx(id);
//}

///**
// * @brief 串口错误回调函数
// */
//void UART_BSP_ErrorCallback(UART_HandleTypeDef *huart)
//{
//    /* 确定是哪个串口 */
//    UART_ID_E id = UART_ID_MAX;
//    
//    if (huart == &huart1) {
//        id = UART_ID_1;
//    } else if (huart == &huart2) {
//        id = UART_ID_2;
//    } else if (huart == &huart3) {
//        id = UART_ID_3;
//    } else {
//        return;
//    }
//    
//    /* 处理错误 */
//    UART_ErrorHandler(id);
//}

///* 私有函数实现 */

///**
// * @brief 初始化发送互斥锁
// */
//static void UART_InitMutex(UART_ID_E id)
//{
//    if (id >= UART_ID_MAX) {
//        return;
//    }
//    
//    UART_Channel_t *channel = &uart_channels[id];
//    
//    if (channel->tx_mutex == NULL) {
//        osMutexDef(uartTxMutex);
//        channel->tx_mutex = osMutexCreate(osMutex(uartTxMutex));
//    }
//}

///**
// * @brief 获取UART HAL句柄
// */
//static UART_HandleTypeDef* UART_GetHuart(UART_ID_E id)
//{
//    switch (id) {
//        case UART_ID_1:
//            return &huart1;
//        case UART_ID_2:
//            return &huart2;
//        case UART_ID_3:
//            return &huart3;
//        default:
//            return NULL;
//    }
//}

///**
// * @brief 处理发送队列
// */
//static void UART_ProcessTxQueue(UART_ID_E id)
//{
//    UART_Channel_t *channel = &uart_channels[id];
//    
//    if (channel->tx_queue == NULL || channel->tx_busy) {
//        return;
//    }
//    
//    /* 从队列中获取发送数据 */
//    osEvent event = osMessageGet(channel->tx_queue, 0);
//    if (event.status == osEventMessage) {
//        uint8_t *tx_data = (uint8_t *)event.value.p;
//        uint16_t tx_size = *(uint16_t *)(tx_data - 2); /* 假设发送数据前有两个字节的长度信息 */
//        
//        /* 复制数据到发送缓冲区 */
//        uint16_t copy_size = (tx_size > channel->tx_buffer_size) ? channel

